<<<<<<< HEAD
print('         ,r\'\"7')
print('r`-_   ,\'  ,/')
print(' \\. ". L_r\'')
print('   `~\\/')
print('      |')
print('      |')
=======
print('         ,r\'\"7')
print('r`-_   ,\'  ,/')
print(' \\. ". L_r\'')
print('   `~\\/')
print('      |')
print('      |')
>>>>>>> 859c2bf (first commit)
